export const SET_FILE_NAMES = 'SET_FILE_NAMES';

export const ADD_PLAYER_TO_LIST = 'ADD_PLAYER_TO_LIST';
export const REMOVE_PLAYER_FROM_LIST = 'REMOVE_PLAYER_FROM_LIST';
export const UPDATE_INGAME_STATE = 'UPDATE_INGAME_STATE';
export const FETCH_PLAYERS_ONLINE = 'FETCH_PLAYERS_ONLINE';
export const SET_PLAYERS_ONLINE = 'SET_PLAYERS_ONLINE';